export const SIKESRA_MIGRATION_FILES = [
	"0001_sikesra_settings_and_catalog.sql",
	"0002_sikesra_regions.sql",
	"0003_sikesra_registry_core.sql",
	"0004_sikesra_detail_tables.sql",
	"0005_sikesra_documents.sql",
	"0006_sikesra_verification.sql",
	"0007_sikesra_imports.sql",
	"0008_sikesra_deduplication.sql",
	"0009_sikesra_access_abac.sql",
	"0010_sikesra_exports_audit.sql",
	"0011_sikesra_core_region_sources.sql",
	"0012_sikesra_field_standards.sql",
	"0013_sikesra_registry_query_indexes.sql",
	"0014_sikesra_custom_attributes.sql",
	"0015_sikesra_delete_governance.sql",
	"0016_sikesra_code_history_corrections.sql",
	"0017_sikesra_delete_snapshot_updated_by.sql",
] as const;
