// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, TaxonomyTerm, PortableTextBlock } from "emdash";

export interface Gallery {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description?: string;
  cover_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  gallery_type: "photo" | "video" | "mixed";
  event_date?: string;
  location?: string;
  layout_variant: "grid" | "masonry" | "carousel" | "slider";
  gallery_items: unknown;
  featured?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface NewsItem {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  summary?: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface PortfolioItem {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description?: string;
  category?: string;
  tech?: unknown;
  url?: string;
  stage?: string;
  featured?: boolean;
  order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  content?: PortableTextBlock[];
  excerpt?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Service {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description?: string;
  icon?: string;
  order?: number;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Testimonial {
  id: string;
  slug: string | null;
  status: string;
  quote: string;
  name?: string;
  role?: string;
  featured?: boolean;
  order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface WebsiteSocialSettings {
  id: string;
  slug: string | null;
  status: string;
  enabled?: boolean;
  whatsapp_number: string;
  default_message?: string;
  hero_message?: string;
  section_message?: string;
  contact_message?: string;
  profile_message?: string;
  services_message?: string;
  posts_message?: string;
  gallery_message?: string;
  news_message?: string;
  widgets_message?: string;
  hero_label?: string;
  section_label?: string;
  contact_label?: string;
  profile_label?: string;
  services_label?: string;
  posts_label?: string;
  gallery_label?: string;
  news_label?: string;
  widgets_label?: string;
  sticky_label?: string;
  maps_embed_url?: string;
  business_address?: string;
  opening_hours?: string;
  google_maps_url?: string;
  schema_type?: string;
  business_name?: string;
  business_description?: string;
  business_phone?: string;
  price_range?: string;
  promo_enabled?: boolean;
  promo_title?: string;
  promo_text?: string;
  promo_price?: string;
  promo_discount?: string;
  promo_cta_message?: string;
  promo_feature_1?: string;
  promo_feature_2?: string;
  promo_feature_3?: string;
  promo_feature_4?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    galleries: Gallery;
    news: NewsItem;
    pages: Page;
    portfolio: PortfolioItem;
    posts: Post;
    services: Service;
    testimonials: Testimonial;
    website_social: WebsiteSocialSettings;
  }
}
