import type {
	SikesraDataModule,
	SikesraFieldDataClass,
	SikesraFieldDataType,
	SikesraFieldGroup,
	SikesraFieldStandardDto,
	SikesraModuleFieldValidationSchema,
} from "./contracts/field-standard-contracts.js";
import { SIKESRA_D1_TABLES } from "./db/schema.js";

export const SIKESRA_DATA_MODULES = [
	"rumah_ibadah",
	"lembaga_keagamaan",
	"pendidikan_keagamaan",
	"lks",
	"guru_agama",
	"anak_yatim",
	"disabilitas",
	"lansia_terlantar",
] as const satisfies readonly SikesraDataModule[];

export const SIKESRA_PERSON_MODULES = [
	"guru_agama",
	"anak_yatim",
	"disabilitas",
	"lansia_terlantar",
] as const;

export const SIKESRA_SENSITIVE_BENEFICIARY_MODULES = [
	"anak_yatim",
	"disabilitas",
	"lansia_terlantar",
] as const;

export const SIKESRA_KTP_ADDRESS_FIELD_KEYS = [
	"alamat_ktp_province_code",
	"alamat_ktp_regency_code",
	"alamat_ktp_district_code",
	"alamat_ktp_village_code",
	"alamat_ktp_detail",
	"alamat_ktp_rt",
	"alamat_ktp_rw",
	"alamat_ktp_postal_code",
] as const;

export const SIKESRA_DOMICILE_ADDRESS_FIELD_KEYS = [
	"alamat_domisili_sama_dengan_ktp",
	"alamat_domisili_province_code",
	"alamat_domisili_regency_code",
	"alamat_domisili_district_code",
	"alamat_domisili_village_code",
	"alamat_domisili_detail",
	"alamat_domisili_rt",
	"alamat_domisili_rw",
	"alamat_domisili_postal_code",
] as const;

const MODULE_DETAIL_TABLES = {
	rumah_ibadah: SIKESRA_D1_TABLES.rumahIbadahDetails,
	lembaga_keagamaan: SIKESRA_D1_TABLES.lembagaKeagamaanDetails,
	pendidikan_keagamaan: SIKESRA_D1_TABLES.pendidikanKeagamaanDetails,
	lks: SIKESRA_D1_TABLES.lksDetails,
	guru_agama: SIKESRA_D1_TABLES.guruAgamaDetails,
	anak_yatim: SIKESRA_D1_TABLES.anakYatimDetails,
	disabilitas: SIKESRA_D1_TABLES.disabilitasDetails,
	lansia_terlantar: SIKESRA_D1_TABLES.lansiaTerlantarDetails,
} as const satisfies Record<SikesraDataModule, string>;

type FieldInput = Omit<SikesraFieldStandardDto, "module">;

function field(module: SikesraDataModule, input: FieldInput): SikesraFieldStandardDto {
	return { module, ...input };
}

function coreFields(module: SikesraDataModule): SikesraFieldStandardDto[] {
	const table = SIKESRA_D1_TABLES.registryEntities;
	return [
		field(module, {
			key: "id",
			label: "Registry ID",
			fieldGroup: "core",
			dataClass: "non_personal",
			required: true,
			dataType: "string",
			maxLength: 80,
			storageTable: table,
			importable: false,
			exportable: true,
			publicSafe: false,
			maskByDefault: false,
			validationRules: ["required", "system_id"],
		}),
		field(module, {
			key: "sikesra_id_20",
			label: "20-digit SIKESRA ID",
			fieldGroup: "core",
			dataClass: "non_personal",
			required: false,
			dataType: "string",
			maxLength: 20,
			storageTable: table,
			importable: false,
			exportable: true,
			publicSafe: false,
			maskByDefault: false,
			validationRules: ["digits:20"],
		}),
		field(module, {
			key: "tenant_id",
			label: "Tenant ID",
			fieldGroup: "audit",
			dataClass: "restricted",
			required: true,
			dataType: "string",
			storageTable: table,
			importable: false,
			exportable: false,
			publicSafe: false,
			maskByDefault: true,
			validationRules: ["required", "system_scope"],
		}),
		field(module, {
			key: "site_id",
			label: "Site ID",
			fieldGroup: "audit",
			dataClass: "restricted",
			required: true,
			dataType: "string",
			storageTable: table,
			importable: false,
			exportable: false,
			publicSafe: false,
			maskByDefault: true,
			validationRules: ["required", "system_scope"],
		}),
		field(module, {
			key: "entity_type",
			label: "Entity Type",
			fieldGroup: "core",
			dataClass: "non_personal",
			required: true,
			dataType: "enum",
			enumValues: [...SIKESRA_DATA_MODULES],
			storageTable: table,
			importable: true,
			exportable: true,
			publicSafe: true,
			maskByDefault: false,
			validationRules: ["required", "known_module"],
		}),
		field(module, {
			key: "subtype_code",
			label: "Subtype Code",
			fieldGroup: "core",
			dataClass: "non_personal",
			required: false,
			dataType: "string",
			maxLength: 80,
			storageTable: table,
			importable: true,
			exportable: true,
			publicSafe: true,
			maskByDefault: false,
			validationRules: ["known_subtype"],
		}),
		field(module, {
			key: "label",
			label: "Display Label",
			fieldGroup: "core",
			dataClass: "non_personal",
			required: true,
			dataType: "string",
			maxLength: 200,
			storageTable: table,
			importable: true,
			exportable: true,
			publicSafe: true,
			maskByDefault: false,
			validationRules: ["required", "max:200"],
		}),
		field(module, {
			key: "public_summary",
			label: "Public Summary",
			fieldGroup: "core",
			dataClass: "non_personal",
			required: false,
			dataType: "string",
			maxLength: 500,
			storageTable: table,
			importable: true,
			exportable: true,
			publicSafe: true,
			maskByDefault: false,
			validationRules: ["max:500", "no_personal_data"],
		}),
		field(module, {
			key: "sensitivity",
			label: "Sensitivity",
			fieldGroup: "core",
			dataClass: "restricted",
			required: true,
			dataType: "enum",
			enumValues: ["public_safe", "internal", "personal", "sensitive", "restricted"],
			storageTable: table,
			importable: false,
			exportable: true,
			publicSafe: false,
			maskByDefault: true,
			validationRules: ["required", "known_sensitivity"],
		}),
		field(module, {
			key: "verification_stage",
			label: "Verification Stage",
			fieldGroup: "verification",
			dataClass: "non_personal",
			required: true,
			dataType: "enum",
			enumValues: [
				"draft",
				"submitted",
				"village_review",
				"district_review",
				"sopd_review",
				"regency_review",
				"verified",
				"needs_revision",
				"rejected",
			],
			storageTable: table,
			importable: false,
			exportable: true,
			publicSafe: true,
			maskByDefault: false,
			validationRules: ["required", "known_verification_stage"],
		}),
		...regionCodeFields(module, table),
		field(module, {
			key: "created_at",
			label: "Created At",
			fieldGroup: "audit",
			dataClass: "restricted",
			required: true,
			dataType: "datetime",
			storageTable: table,
			importable: false,
			exportable: true,
			publicSafe: false,
			maskByDefault: true,
			validationRules: ["system_timestamp"],
		}),
		field(module, {
			key: "updated_at",
			label: "Updated At",
			fieldGroup: "audit",
			dataClass: "restricted",
			required: true,
			dataType: "datetime",
			storageTable: table,
			importable: false,
			exportable: true,
			publicSafe: false,
			maskByDefault: true,
			validationRules: ["system_timestamp"],
		}),
		field(module, {
			key: "deleted_at",
			label: "Deleted At",
			fieldGroup: "audit",
			dataClass: "restricted",
			required: false,
			dataType: "datetime",
			storageTable: table,
			importable: false,
			exportable: false,
			publicSafe: false,
			maskByDefault: true,
			validationRules: ["soft_delete_marker"],
		}),
		field(module, {
			key: "created_by",
			label: "Created By",
			fieldGroup: "audit",
			dataClass: "restricted",
			required: false,
			dataType: "string",
			storageTable: table,
			importable: false,
			exportable: false,
			publicSafe: false,
			maskByDefault: true,
			validationRules: ["emdash_user_reference"],
		}),
		field(module, {
			key: "updated_by",
			label: "Updated By",
			fieldGroup: "audit",
			dataClass: "restricted",
			required: false,
			dataType: "string",
			storageTable: table,
			importable: false,
			exportable: false,
			publicSafe: false,
			maskByDefault: true,
			validationRules: ["emdash_user_reference"],
		}),
	];
}

function regionCodeFields(module: SikesraDataModule, table: string): SikesraFieldStandardDto[] {
	return ["province", "regency", "district", "village"].map((level) =>
		field(module, {
			key: `${level}_code`,
			label: `${title(level)} Code`,
			fieldGroup: "region",
			dataClass: "non_personal",
			required: false,
			dataType: "string",
			maxLength: 20,
			storageTable: table,
			importable: true,
			exportable: true,
			publicSafe: true,
			maskByDefault: false,
			validationRules: ["official_region_code"],
		}),
	);
}

function institutionRegionFields(module: SikesraDataModule): SikesraFieldStandardDto[] {
	const table = MODULE_DETAIL_TABLES[module];
	return [
		...(["province", "regency", "district", "village"] as const).flatMap((level) => [
			field(module, {
				key: `${level}_name`,
				label: `${title(level)} Name`,
				fieldGroup: "region",
				dataClass: "non_personal",
				required: false,
				dataType: "string",
				maxLength: 120,
				storageTable: table,
				importable: true,
				exportable: true,
				publicSafe: true,
				maskByDefault: false,
				validationRules: ["official_or_local_region_name"],
			}),
		]),
		field(module, {
			key: "local_area_code",
			label: "Local Area Code",
			fieldGroup: "region",
			dataClass: "non_personal",
			required: false,
			dataType: "string",
			maxLength: 40,
			storageTable: table,
			importable: true,
			exportable: true,
			publicSafe: true,
			maskByDefault: false,
			validationRules: ["local_region_code"],
		}),
		field(module, {
			key: "local_area_name",
			label: "Local Area Name",
			fieldGroup: "region",
			dataClass: "non_personal",
			required: false,
			dataType: "string",
			maxLength: 120,
			storageTable: table,
			importable: true,
			exportable: true,
			publicSafe: true,
			maskByDefault: false,
			validationRules: ["local_region_name"],
		}),
		field(module, {
			key: "address_text",
			label: "Address",
			fieldGroup: "address",
			dataClass: "non_personal",
			required: false,
			dataType: "string",
			maxLength: 500,
			storageTable: table,
			importable: true,
			exportable: true,
			publicSafe: false,
			maskByDefault: false,
			validationRules: ["max:500", "institution_address"],
		}),
		field(module, {
			key: "latitude",
			label: "Latitude",
			fieldGroup: "region",
			dataClass: "non_personal",
			required: false,
			dataType: "number",
			storageTable: table,
			importable: true,
			exportable: true,
			publicSafe: false,
			maskByDefault: false,
			validationRules: ["latitude"],
		}),
		field(module, {
			key: "longitude",
			label: "Longitude",
			fieldGroup: "region",
			dataClass: "non_personal",
			required: false,
			dataType: "number",
			storageTable: table,
			importable: true,
			exportable: true,
			publicSafe: false,
			maskByDefault: false,
			validationRules: ["longitude"],
		}),
		field(module, {
			key: "geo_accuracy_meters",
			label: "Geo Accuracy Meters",
			fieldGroup: "region",
			dataClass: "non_personal",
			required: false,
			dataType: "number",
			storageTable: table,
			importable: true,
			exportable: true,
			publicSafe: false,
			maskByDefault: false,
			validationRules: ["min:0"],
		}),
	];
}

function personIdentityFields(module: SikesraDataModule): SikesraFieldStandardDto[] {
	const table = SIKESRA_D1_TABLES.personProfiles;
	return [
		field(module, {
			key: "nama_lengkap",
			label: "Full Name",
			fieldGroup: "person",
			dataClass: "personal",
			required: true,
			dataType: "string",
			maxLength: 200,
			storageTable: table,
			importable: true,
			exportable: true,
			publicSafe: false,
			maskByDefault: true,
			validationRules: ["required", "max:200"],
		}),
		field(module, {
			key: module === "anak_yatim" ? "nik_kia" : "nik",
			label: module === "anak_yatim" ? "NIK/KIA" : "NIK",
			fieldGroup: "person",
			dataClass: "sensitive_personal",
			required: true,
			dataType: "string",
			maxLength: 20,
			storageTable: table,
			importable: true,
			exportable: true,
			publicSafe: false,
			maskByDefault: true,
			validationRules: ["required", "identity_number", "restricted_export_reason"],
		}),
		field(module, {
			key: "nomor_kk",
			label: "Family Card Number",
			fieldGroup: "person",
			dataClass: "sensitive_personal",
			required: false,
			dataType: "string",
			maxLength: 20,
			storageTable: table,
			importable: true,
			exportable: true,
			publicSafe: false,
			maskByDefault: true,
			validationRules: ["identity_number", "restricted_export_reason"],
		}),
		field(module, {
			key: "jenis_kelamin",
			label: "Gender",
			fieldGroup: "person",
			dataClass: "personal",
			required: false,
			dataType: "enum",
			enumValues: ["male", "female", "unknown"],
			storageTable: table,
			importable: true,
			exportable: true,
			publicSafe: false,
			maskByDefault: true,
			validationRules: ["known_gender"],
		}),
		field(module, {
			key: "tempat_lahir",
			label: "Birth Place",
			fieldGroup: "person",
			dataClass: "personal",
			required: false,
			dataType: "string",
			maxLength: 120,
			storageTable: table,
			importable: true,
			exportable: true,
			publicSafe: false,
			maskByDefault: true,
			validationRules: ["max:120"],
		}),
		field(module, {
			key: "tanggal_lahir",
			label: "Birth Date",
			fieldGroup: "person",
			dataClass: "personal",
			required: false,
			dataType: "date",
			storageTable: table,
			importable: true,
			exportable: true,
			publicSafe: false,
			maskByDefault: true,
			validationRules: ["date", "not_future"],
		}),
		field(module, {
			key: "nomor_hp",
			label: "Phone Number",
			fieldGroup: "person",
			dataClass: "sensitive_personal",
			required: false,
			dataType: "string",
			maxLength: 30,
			storageTable: table,
			importable: true,
			exportable: true,
			publicSafe: false,
			maskByDefault: true,
			validationRules: ["phone", "restricted_export_reason"],
		}),
		field(module, {
			key: "email",
			label: "Email",
			fieldGroup: "person",
			dataClass: "personal",
			required: false,
			dataType: "string",
			maxLength: 200,
			storageTable: table,
			importable: true,
			exportable: true,
			publicSafe: false,
			maskByDefault: true,
			validationRules: ["email"],
		}),
		...personalAddressFields(module),
	];
}

function personalAddressFields(module: SikesraDataModule): SikesraFieldStandardDto[] {
	const table = SIKESRA_D1_TABLES.personProfiles;
	return [...SIKESRA_KTP_ADDRESS_FIELD_KEYS, ...SIKESRA_DOMICILE_ADDRESS_FIELD_KEYS].map((key) =>
		field(module, {
			key,
			label: addressLabel(key),
			fieldGroup: "address",
			dataClass: key === "alamat_domisili_sama_dengan_ktp" ? "personal" : "sensitive_personal",
			required:
				SIKESRA_KTP_ADDRESS_FIELD_KEYS.includes(key as never) ||
				key === "alamat_domisili_sama_dengan_ktp",
			dataType: key === "alamat_domisili_sama_dengan_ktp" ? "boolean" : "string",
			maxLength: key.endsWith("_detail") ? 500 : 40,
			storageTable: table,
			importable: true,
			exportable: true,
			publicSafe: false,
			maskByDefault: true,
			validationRules:
				key === "alamat_domisili_sama_dengan_ktp"
					? ["boolean", "store_normalized_domicile_snapshot"]
					: ["personal_address", "restricted_export_reason"],
			notes: key.startsWith("alamat_ktp_")
				? "KTP address field; never public-safe."
				: "Domicile address field; never public-safe.",
		}),
	);
}

function detailField(
	module: SikesraDataModule,
	key: string,
	label: string,
	fieldGroup: SikesraFieldGroup,
	dataClass: SikesraFieldDataClass,
	required = false,
	dataType: SikesraFieldDataType = "string",
	validationRules: string[] = [],
): SikesraFieldStandardDto {
	return field(module, {
		key,
		label,
		fieldGroup,
		dataClass,
		required,
		dataType,
		storageTable: MODULE_DETAIL_TABLES[module],
		importable: true,
		exportable: dataClass !== "restricted",
		publicSafe: false,
		maskByDefault: dataClass !== "non_personal",
		validationRules: required ? ["required", ...validationRules] : validationRules,
	});
}

function institutionContactFields(
	module: SikesraDataModule,
	role: "pengurus" | "ketua" | "pimpinan" | "operator",
): SikesraFieldStandardDto[] {
	return [
		detailField(
			module,
			`nama_${role}`,
			`${title(role)} Name`,
			"person",
			"personal",
			false,
			"string",
			["max:200"],
		),
		detailField(
			module,
			`nomor_hp_${role}`,
			`${title(role)} Phone`,
			"person",
			"personal",
			false,
			"string",
			["phone", "mask_by_default"],
		),
		detailField(
			module,
			`email_${role}`,
			`${title(role)} Email`,
			"person",
			"personal",
			false,
			"string",
			["email", "mask_by_default"],
		),
	];
}

const MODULE_SPECIFIC_FIELDS: Record<SikesraDataModule, SikesraFieldStandardDto[]> = {
	rumah_ibadah: [
		...institutionRegionFields("rumah_ibadah"),
		detailField(
			"rumah_ibadah",
			"nama_rumah_ibadah",
			"House of Worship Name",
			"institution",
			"non_personal",
			true,
			"string",
			["max:200"],
		),
		detailField(
			"rumah_ibadah",
			"jenis_rumah_ibadah",
			"House of Worship Type",
			"institution",
			"non_personal",
			true,
			"enum",
			["known_religious_place_type"],
		),
		detailField(
			"rumah_ibadah",
			"nomor_registrasi",
			"Registration Number",
			"institution",
			"non_personal",
			false,
			"string",
			["max:80"],
		),
		detailField("rumah_ibadah", "status_tanah", "Land Status", "institution", "non_personal"),
		detailField(
			"rumah_ibadah",
			"status_bangunan",
			"Building Status",
			"institution",
			"non_personal",
		),
		detailField(
			"rumah_ibadah",
			"luas_tanah_m2",
			"Land Area m2",
			"institution",
			"non_personal",
			false,
			"number",
			["min:0"],
		),
		detailField(
			"rumah_ibadah",
			"luas_bangunan_m2",
			"Building Area m2",
			"institution",
			"non_personal",
			false,
			"number",
			["min:0"],
		),
		detailField(
			"rumah_ibadah",
			"daya_tampung_jamaah",
			"Congregation Capacity",
			"institution",
			"non_personal",
			false,
			"number",
			["min:0"],
		),
		detailField(
			"rumah_ibadah",
			"tahun_berdiri",
			"Established Year",
			"institution",
			"non_personal",
			false,
			"number",
			["year"],
		),
		detailField(
			"rumah_ibadah",
			"status_aktif",
			"Active Status",
			"institution",
			"non_personal",
			false,
			"boolean",
		),
		detailField(
			"rumah_ibadah",
			"catatan_umum",
			"General Notes",
			"institution",
			"non_personal",
			false,
			"string",
			["no_personal_data"],
		),
		...institutionContactFields("rumah_ibadah", "pengurus"),
	],
	lembaga_keagamaan: [
		...institutionRegionFields("lembaga_keagamaan"),
		detailField(
			"lembaga_keagamaan",
			"nama_lembaga",
			"Organization Name",
			"institution",
			"non_personal",
			true,
			"string",
			["max:200"],
		),
		detailField(
			"lembaga_keagamaan",
			"jenis_lembaga",
			"Organization Type",
			"institution",
			"non_personal",
			true,
			"enum",
			["known_religious_organization_type"],
		),
		detailField(
			"lembaga_keagamaan",
			"nomor_registrasi",
			"Registration Number",
			"institution",
			"non_personal",
		),
		detailField(
			"lembaga_keagamaan",
			"wilayah_layanan",
			"Service Area",
			"institution",
			"non_personal",
			false,
			"string",
		),
		detailField(
			"lembaga_keagamaan",
			"status_aktif",
			"Active Status",
			"institution",
			"non_personal",
			false,
			"boolean",
		),
		detailField(
			"lembaga_keagamaan",
			"tahun_berdiri",
			"Established Year",
			"institution",
			"non_personal",
			false,
			"number",
			["year"],
		),
		detailField(
			"lembaga_keagamaan",
			"jumlah_pengurus",
			"Administrator Count",
			"institution",
			"non_personal",
			false,
			"number",
			["min:0"],
		),
		detailField(
			"lembaga_keagamaan",
			"jumlah_anggota",
			"Member Count",
			"institution",
			"non_personal",
			false,
			"number",
			["min:0"],
		),
		detailField(
			"lembaga_keagamaan",
			"nik_ketua",
			"Chairperson NIK",
			"person",
			"sensitive_personal",
			false,
			"string",
			["identity_number", "restricted_export_reason"],
		),
		...institutionContactFields("lembaga_keagamaan", "ketua"),
		...institutionContactFields("lembaga_keagamaan", "operator"),
	],
	pendidikan_keagamaan: [
		...institutionRegionFields("pendidikan_keagamaan"),
		detailField(
			"pendidikan_keagamaan",
			"nama_lembaga_pendidikan",
			"Education Institution Name",
			"institution",
			"non_personal",
			true,
			"string",
			["max:200"],
		),
		detailField(
			"pendidikan_keagamaan",
			"jenis_pendidikan_keagamaan",
			"Religious Education Type",
			"institution",
			"non_personal",
			true,
			"enum",
			["known_religious_education_type"],
		),
		detailField(
			"pendidikan_keagamaan",
			"nomor_izin_operasional",
			"Operational Permit Number",
			"institution",
			"non_personal",
		),
		detailField(
			"pendidikan_keagamaan",
			"status_aktif",
			"Active Status",
			"institution",
			"non_personal",
			false,
			"boolean",
		),
		detailField(
			"pendidikan_keagamaan",
			"jumlah_santri_siswa",
			"Student Count",
			"institution",
			"non_personal",
			false,
			"number",
			["aggregate_only", "min:0"],
		),
		detailField(
			"pendidikan_keagamaan",
			"jumlah_pengajar",
			"Teacher Count",
			"institution",
			"non_personal",
			false,
			"number",
			["aggregate_only", "min:0"],
		),
		detailField(
			"pendidikan_keagamaan",
			"jenjang_pendidikan",
			"Education Level",
			"institution",
			"non_personal",
		),
		detailField(
			"pendidikan_keagamaan",
			"kurikulum_utama",
			"Primary Curriculum",
			"institution",
			"non_personal",
		),
		detailField(
			"pendidikan_keagamaan",
			"fasilitas_utama",
			"Main Facilities",
			"institution",
			"non_personal",
			false,
			"json",
		),
		detailField(
			"pendidikan_keagamaan",
			"nik_pimpinan",
			"Leader NIK",
			"person",
			"sensitive_personal",
			false,
			"string",
			["identity_number", "restricted_export_reason"],
		),
		...institutionContactFields("pendidikan_keagamaan", "pimpinan"),
		...institutionContactFields("pendidikan_keagamaan", "operator"),
	],
	lks: [
		...institutionRegionFields("lks"),
		detailField("lks", "nama_lks", "LKS Name", "institution", "non_personal", true, "string", [
			"max:200",
		]),
		detailField("lks", "jenis_lks", "LKS Type", "institution", "non_personal", true, "enum", [
			"known_lks_type",
		]),
		detailField("lks", "nomor_izin", "Permit Number", "institution", "non_personal"),
		detailField(
			"lks",
			"kapasitas_layanan",
			"Service Capacity",
			"institution",
			"non_personal",
			false,
			"number",
			["min:0"],
		),
		detailField(
			"lks",
			"jumlah_penerima_manfaat_agregat",
			"Beneficiary Aggregate Count",
			"welfare",
			"non_personal",
			false,
			"number",
			["aggregate_only", "small_cell_suppression"],
		),
		detailField("lks", "jenis_layanan", "Service Type", "welfare", "non_personal", false, "json"),
		detailField(
			"lks",
			"beneficiary_profile_id",
			"Beneficiary Profile ID",
			"welfare",
			"restricted",
			false,
			"string",
			["person_profile_reference", "restricted_export_reason"],
		),
		detailField(
			"lks",
			"kondisi_sosial",
			"Social Condition",
			"welfare",
			"sensitive_personal",
			false,
			"string",
			["mask_by_default", "restricted_export_reason"],
		),
		detailField(
			"lks",
			"kondisi_kesehatan_ringkas",
			"Health Summary",
			"welfare",
			"sensitive_personal",
			false,
			"string",
			["mask_by_default", "restricted_export_reason"],
		),
		detailField(
			"lks",
			"keterangan_kerentanan",
			"Vulnerability Notes",
			"welfare",
			"restricted",
			false,
			"string",
			["mask_by_default", "restricted_export_reason"],
		),
		...institutionContactFields("lks", "pimpinan"),
		...institutionContactFields("lks", "operator"),
	],
	guru_agama: [
		...personIdentityFields("guru_agama"),
		detailField("guru_agama", "agama", "Religion", "person", "personal", false, "enum", [
			"known_religion",
		]),
		detailField("guru_agama", "pendidikan_terakhir", "Latest Education", "person", "personal"),
		detailField("guru_agama", "status_kepegawaian", "Employment Status", "person", "personal"),
		detailField("guru_agama", "tempat_mengajar", "Teaching Place", "institution", "non_personal"),
		detailField(
			"guru_agama",
			"mata_pelajaran_agama",
			"Religious Subject",
			"institution",
			"non_personal",
		),
		detailField(
			"guru_agama",
			"nomor_sk",
			"Assignment Decree Number",
			"verification",
			"restricted",
			false,
			"string",
			["restricted_export_reason"],
		),
		detailField(
			"guru_agama",
			"jenis_guru_agama",
			"Religious Teacher Type",
			"institution",
			"non_personal",
			true,
			"enum",
			["known_teacher_type"],
		),
		detailField("guru_agama", "wilayah_tugas", "Work Region", "region", "non_personal"),
	],
	anak_yatim: [
		...personIdentityFields("anak_yatim"),
		detailField(
			"anak_yatim",
			"nama_wali",
			"Guardian Name",
			"person",
			"sensitive_personal",
			true,
			"string",
			["mask_by_default"],
		),
		detailField("anak_yatim", "hubungan_wali", "Guardian Relationship", "person", "personal"),
		detailField(
			"anak_yatim",
			"nomor_hp_wali",
			"Guardian Phone",
			"person",
			"sensitive_personal",
			false,
			"string",
			["phone", "restricted_export_reason"],
		),
		detailField(
			"anak_yatim",
			"status_sekolah",
			"School Status",
			"welfare",
			"sensitive_personal",
			false,
			"enum",
			["known_school_status"],
		),
		detailField(
			"anak_yatim",
			"nama_sekolah",
			"School Name",
			"welfare",
			"sensitive_personal",
			false,
			"string",
			["mask_by_default"],
		),
		detailField(
			"anak_yatim",
			"status_yatim_piatu",
			"Orphan Status",
			"welfare",
			"sensitive_personal",
			true,
			"enum",
			["known_orphan_status"],
		),
		detailField(
			"anak_yatim",
			"kondisi_ekonomi",
			"Economic Condition",
			"welfare",
			"sensitive_personal",
			false,
			"string",
			["restricted_export_reason"],
		),
		detailField(
			"anak_yatim",
			"kategori_usia",
			"Age Category",
			"welfare",
			"non_personal",
			false,
			"enum",
			["aggregate_only"],
		),
		detailField(
			"anak_yatim",
			"status_bantuan",
			"Assistance Status",
			"welfare",
			"sensitive_personal",
			false,
			"enum",
			["small_cell_suppression"],
		),
	],
	disabilitas: [
		...personIdentityFields("disabilitas"),
		detailField(
			"disabilitas",
			"nama_wali_pendamping",
			"Companion Name",
			"person",
			"sensitive_personal",
			false,
			"string",
			["mask_by_default"],
		),
		detailField(
			"disabilitas",
			"nomor_hp_wali_pendamping",
			"Companion Phone",
			"person",
			"sensitive_personal",
			false,
			"string",
			["phone", "restricted_export_reason"],
		),
		detailField(
			"disabilitas",
			"jenis_disabilitas",
			"Disability Type",
			"welfare",
			"sensitive_personal",
			true,
			"enum",
			["health_related", "restricted_export_reason"],
		),
		detailField(
			"disabilitas",
			"derajat_disabilitas",
			"Disability Degree",
			"welfare",
			"sensitive_personal",
			false,
			"enum",
			["health_related", "restricted_export_reason"],
		),
		detailField(
			"disabilitas",
			"kebutuhan_bantuan",
			"Assistance Need",
			"welfare",
			"sensitive_personal",
			false,
			"string",
			["small_cell_suppression"],
		),
		detailField(
			"disabilitas",
			"kondisi_kesehatan_ringkas",
			"Health Summary",
			"welfare",
			"restricted",
			false,
			"string",
			["health_related", "restricted_export_reason"],
		),
		detailField(
			"disabilitas",
			"alat_bantu",
			"Assistive Device",
			"welfare",
			"sensitive_personal",
			false,
			"string",
		),
		detailField(
			"disabilitas",
			"dokumen_pendukung_id",
			"Supporting Document ID",
			"document",
			"restricted",
			false,
			"string",
			["document_reference"],
		),
	],
	lansia_terlantar: [
		...personIdentityFields("lansia_terlantar"),
		detailField(
			"lansia_terlantar",
			"nama_keluarga_pendamping",
			"Family Companion Name",
			"person",
			"sensitive_personal",
			false,
			"string",
			["mask_by_default"],
		),
		detailField(
			"lansia_terlantar",
			"hubungan_pendamping",
			"Companion Relationship",
			"person",
			"personal",
		),
		detailField(
			"lansia_terlantar",
			"nomor_hp_pendamping",
			"Companion Phone",
			"person",
			"sensitive_personal",
			false,
			"string",
			["phone", "restricted_export_reason"],
		),
		detailField(
			"lansia_terlantar",
			"kondisi_kesehatan_ringkas",
			"Health Summary",
			"welfare",
			"restricted",
			false,
			"string",
			["health_related", "restricted_export_reason"],
		),
		detailField(
			"lansia_terlantar",
			"kondisi_sosial",
			"Social Condition",
			"welfare",
			"sensitive_personal",
			false,
			"string",
			["restricted_export_reason"],
		),
		detailField(
			"lansia_terlantar",
			"status_tempat_tinggal",
			"Residence Status",
			"welfare",
			"sensitive_personal",
			false,
			"string",
		),
		detailField(
			"lansia_terlantar",
			"kebutuhan_bantuan",
			"Assistance Need",
			"welfare",
			"sensitive_personal",
			false,
			"string",
			["small_cell_suppression"],
		),
		detailField(
			"lansia_terlantar",
			"status_bantuan",
			"Assistance Status",
			"welfare",
			"sensitive_personal",
			false,
			"enum",
			["small_cell_suppression"],
		),
		detailField(
			"lansia_terlantar",
			"kategori_usia",
			"Age Category",
			"welfare",
			"non_personal",
			false,
			"enum",
			["aggregate_only"],
		),
	],
};

export const SIKESRA_FIELD_STANDARDS = SIKESRA_DATA_MODULES.flatMap((module) => [
	...coreFields(module),
	...MODULE_SPECIFIC_FIELDS[module],
]) satisfies SikesraFieldStandardDto[];

export const SIKESRA_MODULE_FIELD_VALIDATION_SCHEMAS = SIKESRA_DATA_MODULES.map((module) => {
	const standards = SIKESRA_FIELD_STANDARDS.filter((standard) => standard.module === module);
	const restrictedExportFields = standards
		.filter(
			(standard) =>
				standard.dataClass === "sensitive_personal" ||
				standard.dataClass === "restricted" ||
				standard.validationRules.includes("restricted_export_reason"),
		)
		.map((standard) => standard.key);
	return {
		module,
		requiredFields: standards
			.filter((standard) => standard.required)
			.map((standard) => standard.key),
		importableFields: standards
			.filter((standard) => standard.importable)
			.map((standard) => standard.key),
		exportableFields: standards
			.filter((standard) => standard.exportable)
			.map((standard) => standard.key),
		publicSafeFields: standards
			.filter((standard) => standard.publicSafe)
			.map((standard) => standard.key),
		ktpAddressFields: standards
			.filter((standard) => standard.key.startsWith("alamat_ktp_"))
			.map((standard) => standard.key),
		domicileAddressFields: standards
			.filter((standard) => standard.key.startsWith("alamat_domisili_"))
			.map((standard) => standard.key),
		restrictedExportFields,
	};
}) satisfies SikesraModuleFieldValidationSchema[];

export function getSikesraFieldStandardsForModule(
	module: SikesraDataModule,
): SikesraFieldStandardDto[] {
	return SIKESRA_FIELD_STANDARDS.filter((standard) => standard.module === module);
}

export function getSikesraFieldValidationSchema(
	module: SikesraDataModule,
): SikesraModuleFieldValidationSchema {
	const schema = SIKESRA_MODULE_FIELD_VALIDATION_SCHEMAS.find((item) => item.module === module);
	if (!schema) throw new Error(`Unknown SIKESRA module: ${module}`);
	return schema;
}

function title(value: string): string {
	return value
		.split("_")
		.map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
		.join(" ");
}

function addressLabel(key: string): string {
	return title(key.replace("alamat_", "").replace("ktp", "KTP"));
}
