export const AWCMS_SIKESRA_PERMISSIONS = {
	dashboardRead: "awcms:sikesra:dashboard:read",
	settingsRead: "awcms:sikesra:settings:read",
	settingsUpdate: "awcms:sikesra:settings:update",
	auditRead: "awcms:sikesra:audit:read",
	publicStatusRead: "awcms:sikesra:public-status:read",
	stateTouch: "awcms:sikesra:state:touch",
	permissionCatalogRead: "awcms:sikesra:permissions:read",
	permissionCatalogWrite: "awcms:sikesra:permissions:write",
	roleCatalogRead: "awcms:sikesra:roles:read",
	roleCatalogWrite: "awcms:sikesra:roles:write",
	accessPreviewRead: "awcms:sikesra:access-preview:read",
	abacAttributeRead: "awcms:sikesra:abac-attributes:read",
	abacAttributeWrite: "awcms:sikesra:abac-attributes:write",
	abacPolicyRead: "awcms:sikesra:abac-policies:read",
	abacPolicyWrite: "awcms:sikesra:abac-policies:write",
	abacPreviewRead: "awcms:sikesra:abac-preview:read",
	sikesraDashboardRead: "sikesra.dashboard.read",
	sikesraRegistryRead: "sikesra.registry.read",
	sikesraRegistryCreate: "sikesra.registry.create",
	sikesraRegistryUpdate: "sikesra.registry.update",
	sikesraRegistryDeleteSoft: "sikesra.registry.delete_soft",
	sikesraRegistryReadSensitive: "sikesra.registry.read_sensitive",
	sikesraDocumentRead: "sikesra.document.read",
	sikesraDocumentUpload: "sikesra.document.upload",
	sikesraDocumentReadRestricted: "sikesra.document.read_restricted",
	sikesraImportCreate: "sikesra.import.create",
	sikesraImportValidate: "sikesra.import.validate",
	sikesraImportPromote: "sikesra.import.promote",
	sikesraVerificationRead: "sikesra.verification.read",
	sikesraVerificationApprove: "sikesra.verification.approve",
	sikesraVerificationReject: "sikesra.verification.reject",
	sikesraReportRead: "sikesra.report.read",
	sikesraExportCreate: "sikesra.export.create",
	sikesraExportRestricted: "sikesra.export.restricted",
	sikesraAuditRead: "sikesra.audit.read",
	sikesraSettingsRead: "sikesra.settings.read",
	sikesraSettingsUpdate: "sikesra.settings.update",
	sikesraRbacManage: "sikesra.rbac.manage",
	sikesraAbacManage: "sikesra.abac.manage",
	sikesraLifecycleCreate: "sikesra.lifecycle.create",
	sikesraLifecycleReadList: "sikesra.lifecycle.read_list",
	sikesraLifecycleReadDetail: "sikesra.lifecycle.read_detail",
	sikesraLifecycleUpdate: "sikesra.lifecycle.update",
	sikesraLifecycleSoftDelete: "sikesra.lifecycle.soft_delete",
	sikesraLifecycleRestore: "sikesra.lifecycle.restore",
	sikesraLifecycleArchive: "sikesra.lifecycle.archive",
	sikesraLifecyclePermanentDelete: "sikesra.lifecycle.permanent_delete",
	sikesraCustomAttributeRead: "sikesra.custom_attribute.read",
	sikesraCustomAttributeCreate: "sikesra.custom_attribute.create",
	sikesraCustomAttributeUpdate: "sikesra.custom_attribute.update",
	sikesraCustomAttributeDeleteSoft: "sikesra.custom_attribute.delete_soft",
	sikesraCustomAttributeManageSystem: "sikesra.custom_attribute.manage_system",
	sikesraCustomAttributeReadSensitive: "sikesra.custom_attribute.read_sensitive",
	sikesraCustomAttributeExport: "sikesra.custom_attribute.export",
	sikesraCustomAttributeImport: "sikesra.custom_attribute.import",
	sikesraPermanentDeleteRequest: "sikesra.permanent_delete.request",
	sikesraPermanentDeleteApprove: "sikesra.permanent_delete.approve",
	sikesraPermanentDeleteReview: "sikesra.permanent_delete.review",
	sikesraPermanentDeleteCancel: "sikesra.permanent_delete.cancel",
	sikesraPermanentDeleteExecute: "sikesra.permanent_delete.execute",
} as const;

export const AWCMS_SIKESRA_CRUD_PERMISSION_LIST = [
	"sikesra.registry.soft_delete",
	"sikesra.registry.restore",
	"sikesra.registry.permanent_delete",
	"sikesra.person.create",
	"sikesra.person.read",
	"sikesra.person.read_sensitive",
	"sikesra.person.update",
	"sikesra.person.soft_delete",
	"sikesra.person.restore",
	"sikesra.person.permanent_delete",
	"sikesra.module_detail.create",
	"sikesra.module_detail.read",
	"sikesra.module_detail.update",
	"sikesra.module_detail.soft_delete",
	"sikesra.module_detail.restore",
	"sikesra.module_detail.permanent_delete",
	"sikesra.document.create",
	"sikesra.document.update",
	"sikesra.document.soft_delete",
	"sikesra.document.restore",
	"sikesra.document.permanent_delete",
	"sikesra.file_metadata.read",
	"sikesra.file_metadata.create",
	"sikesra.file_metadata.update",
	"sikesra.file_metadata.soft_delete",
	"sikesra.file_metadata.restore",
	"sikesra.file_metadata.permanent_delete",
	"sikesra.import.read",
	"sikesra.import.update",
	"sikesra.import.soft_delete",
	"sikesra.import.restore",
	"sikesra.import.permanent_delete",
	"sikesra.export.read",
	"sikesra.export.update",
	"sikesra.export.cancel",
	"sikesra.export.soft_delete",
	"sikesra.export.restore",
	"sikesra.export.permanent_delete",
	"sikesra.report.configure",
	"sikesra.verification.create",
	"sikesra.verification.update",
	"sikesra.verification.soft_delete",
	"sikesra.verification.restore",
	"sikesra.verification.permanent_delete",
	"sikesra.settings.create",
	"sikesra.settings.soft_delete",
	"sikesra.settings.restore",
	"sikesra.settings.permanent_delete",
	"sikesra.region.create",
	"sikesra.region.read",
	"sikesra.region.update",
	"sikesra.region.soft_delete",
	"sikesra.region.restore",
	"sikesra.region.permanent_delete",
	"sikesra.data_type.create",
	"sikesra.data_type.read",
	"sikesra.data_type.update",
	"sikesra.data_type.soft_delete",
	"sikesra.data_type.restore",
	"sikesra.data_type.permanent_delete",
	"sikesra.field_standard.create",
	"sikesra.field_standard.read",
	"sikesra.field_standard.update",
	"sikesra.field_standard.soft_delete",
	"sikesra.field_standard.restore",
	"sikesra.field_standard.permanent_delete",
	"sikesra.custom_attribute.soft_delete",
	"sikesra.custom_attribute.restore",
	"sikesra.custom_attribute.permanent_delete",
	"sikesra.custom_attribute_value.create",
	"sikesra.custom_attribute_value.read",
	"sikesra.custom_attribute_value.update",
	"sikesra.custom_attribute_value.soft_delete",
	"sikesra.custom_attribute_value.restore",
	"sikesra.custom_attribute_value.permanent_delete",
	"sikesra.rbac.create",
	"sikesra.rbac.read",
	"sikesra.rbac.update",
	"sikesra.rbac.soft_delete",
	"sikesra.rbac.restore",
	"sikesra.rbac.permanent_delete",
	"sikesra.abac.create",
	"sikesra.abac.read",
	"sikesra.abac.update",
	"sikesra.abac.soft_delete",
	"sikesra.abac.restore",
	"sikesra.abac.permanent_delete",
	"sikesra.user_assignment.create",
	"sikesra.user_assignment.read",
	"sikesra.user_assignment.update",
	"sikesra.user_assignment.soft_delete",
	"sikesra.user_assignment.restore",
	"sikesra.user_assignment.permanent_delete",
	"sikesra.audit.export",
	"sikesra.audit.retention_purge_request",
	"sikesra.audit.retention_purge_approve",
	"sikesra.audit.retention_purge_execute",
] as const;

export const AWCMS_SIKESRA_PERMISSION_LIST = [
	...new Set([...Object.values(AWCMS_SIKESRA_PERMISSIONS), ...AWCMS_SIKESRA_CRUD_PERMISSION_LIST]),
];
